### ISSUE TITLE
What happens when part of an event batch fails?

### ISSUE THREAD

**Issue by wetzler** [keenlabs/KeenClient-Node#25]
This question came into Keen IO support chat from a user:

I'm using your nodejs api and It's a little unclear in your documentation what an error is. It seems that if I use the addEvents method to send multiple events I get an array back that gives me the status of each event sent.

Does this mean some events may be injected and some may fail? Also will the error object in the callback be set if only some events got through? 

The example in the documentation for the node api seems oversimplified, it shows that if there was no error, then everything worked great, if there was an error, it failed. I'm wondering when an error is thrown. I seem to be getting no errors thrown, a 200 back and still missing events. 

I've been digging into your api documentation further and see the response with the array of successes and failures on a per event level. It's not clear when an error actually occurs and the examples seem to imply if you don't get an error in the callback method then all your events are safe. Is this true or do I need to do additional checking?

**Comment by dustinlarimer** [comment]
Updated in keen-js: https://github.com/keen/keen-js#api-response-for-saving-a-single-event-1
