### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by bigthyme** [keenlabs/KeenClient-Node#32]
Getting fatal socket hang ups from my node process that is trying to simply send an event via the `addEvent` method; here are the ports the process is working with: 

```
node    13074 root   12u  IPv4 295831087      0t0       TCP public:46096->108.168.254.8-static.reverse.softlayer.com:https (CLOSE_WAIT)
node    13074 root   13u  IPv4 295831088      0t0       TCP public:33911->108.168.254.95-static.reverse.softlayer.com:https (CLOSE_WAIT)
node    13074 root   14u  IPv4 295831089      0t0       TCP public:42734->108.168.254.130-static.reverse.softlayer.com:https (CLOSE_WAIT)
node    13074 root   15u  IPv4 295831090      0t0       TCP public:40130->108.168.254.98-static.reverse.softlayer.com:https (CLOSE_WAIT)
```

I'm using `keen.io: 0.1.2` in my package.json and running node `v0.10.21`

**Comment by xrapz** [comment]
This issue is deprecated. Let's focus on our 3 core packages:
https://github.com/keen/keen-tracking.js
https://github.com/keen/keen-analysis.js
https://github.com/keen/keen-dataviz.js
