### ISSUE TITLE
Error callback being call mutiple times

### ISSUE THREAD

**Issue by parisholley** [keenlabs/KeenClient-Node#34]
If you run more than one query at a time (and say you hit your query limit), the callback is invoked more than once per query, this seems like unexpected behavior. Would recommend updating query.js to use async library

**Comment by xrapz** [comment]
This issue is deprecated. Let's focus on our 3 core packages:
https://github.com/keen/keen-tracking.js
https://github.com/keen/keen-analysis.js
https://github.com/keen/keen-dataviz.js
