### ISSUE TITLE
Oh no, an error! { [Error: Resource not found.] code: 'ResourceNotFoundError' }

### ISSUE THREAD

**Issue by Student007** [keenlabs/KeenClient-Node#36]
Based on your current example code using real projectId and keys:

```
var Keen = require('keen.io');
// Configuration
var config = require('./config.json');
//console.log("config: ",config);

//console.log("Setting up Keen...",config);
var client = Keen.configure({
  projectId: config.masterKey,
  writeKey: config.writeKey,
  readKey: config.readKey,
  protocol: config.protocol
});
client.baseUrl = 'http://api.keen.io/3.0/';


// send single event to Keen IO 
client.addEvent("my event collection", {"property name": "property value"}, function(err, res) {
    if (err) {
        console.log("Oh no, an error!",err);
    } else {
        console.log("Hooray, it worked!");
    }
});

// send multiple events to Keen IO 
client.addEvents({
    "my first event collection": [{"property name": "property value"}],
    "my second event collection": [{"property name2": "property value 2"}]
}, function(err, res) {
    if (err) {
        console.log("Oh no, an error!",err);
    } else {
        console.log("Hooray, it worked!");
    }
});
```

1) I had to override the https url by using protocol=http
2) I got the `resouce not found` error

> Oh no, an error! { [Error: Resource not found.] code: 'ResourceNotFoundError' }
> Oh no, an error! { [Error: Resource not found.] code: 'ResourceNotFoundError' }

I played around with your keen-js but it isn't what I need for Tessel. So please fix this issues :-) ... I am not able to do my own - too less information about the API. Think you would be much faster. I played around some days already.

**Comment by xrapz** [comment]
This issue is deprecated. Let's focus on our 3 core packages:
https://github.com/keen/keen-tracking.js
https://github.com/keen/keen-analysis.js
https://github.com/keen/keen-dataviz.js
